export const classs = [
  { label: "video.all", value: "all" },
  { label: "video.class.cn", value: "cn" },
  { label: "video.class.hktw", value: "hktw" },
  { label: "video.class.ja", value: "ja" },
  { label: "video.class.ko", value: "ko" },
  { label: "video.class.euus", value: "euus" },
  { label: "video.class.other", value: "other" },
];
export const types = [
  { label: "video.all", value: "all" },
  { label: "video.type.love", value: "love" },
  { label: "video.type.costume", value: "costume" },
  { label: "video.type.history", value: "history" },
  { label: "video.type.scifi", value: "scifi" },
  { label: "video.type.martial", value: "martial" },
  { label: "video.type.crime", value: "crime" },
  { label: "video.type.family", value: "family" },
  { label: "video.type.war", value: "war" },
  { label: "video.type.suspense", value: "suspense" },
  { label: "video.type.horror", value: "horror" },
  { label: "video.type.action", value: "action" },
  { label: "video.type.thriller", value: "thriller" },
  { label: "video.type.fantasy", value: "fantasy" },
  { label: "video.type.adventure", value: "adventure" },
  { label: "video.type.comedy", value: "comedy" },
];
