name: GitHub Actions Build and Deploy Page
on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: project
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
  
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm i -g yarn pnpm

      #- name: Build Page
      #  run: |
      #    echo ${{ steps.project.outputs }}
      #    rm -rf node_modules && yarn install
      #    yarn build:page
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        #uses: actions/upload-artifact@v3
        with:
          # Upload entire repository
          path: "./dist"

  # Deployment job
  electron:
    environment:
      name: github-pages
      url: ${{ steps.electron.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ./
      - name: Build Electron
        id: electron
        run: |
          echo "build electron"        
          ls -R
          cd ./github-pages
          ls -R
      
      - name: tar-linux
        if: runner.os == 'Linux'
        run: |
          ls -R
          
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2


