name: Build Android

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Build
        run: |
          npm i -g yarn
          yarn
          pwd && ls -lh
          yarn build 
          cd capacitor
          pwd && ls -lh
          yarn 
          yarn sync
          cd android 
          pwd && ls -lh
          chmod +x ./gradlew
          ./gradlew assembleRelease
          pwd && ls -lh
          cd app/
          pwd && ls -lh
          cd build/ 
          pwd && ls -lh && cd ../
          cd ../
          pwd && ls -lh
          #Extract Android signing key from env
          echo "${{ secrets.RELEASE_KEYSTORE }}" > release.jks.base64
          base64 -d release.jks.base64 > release.decrypted.jks

          # Sign dev build
          # jarsigner -keystore release.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab release

      - name: Upload release bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: capacitor/android/app/build/outputs/bundle/release/app-release-signed.aab
          retention-days: 60