name: Deploy-Docker
on:
  push:
    tags:
      - "v*"
    branches:
      - "dev1"
permissions:
  contents: write

env:
  APP_NAME: vmgc

jobs:
  release:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      # 使用 tyankatsu0105/read-package-version-actions@v1 工具来读取对应的package.json 数据
      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        with:
          path: ""
        id: appinfo

      - name: 展示版本
        run: echo " ${{ env.APP_NAME }} ${{ steps.appinfo.outputs.version }} "
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      # - name: Login to AliyunCS
      #   uses: docker/login-action@v1
      #   with:
      #     registry: registry.cn-beijing.aliyuncs.com
      #     username: ${{ secrets.ALI_USER  }}
      #     password: ${{ secrets.ALI_PASSWORD  }}
      # "registry.cn-beijing.aliyuncs.com/mereith/vanblog:latest"
      # "registry.cn-beijing.aliyuncs.com/mereith/vanblog:${{ steps.appinfo.outputs.version }}"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 打包镜像并推送
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          build-args: |
            VAN_BLOG_BUILD_SERVER=http://localhost:3000
            VAN_BLOG_VERSIONS=${{ steps.appinfo.outputs.version }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            "docker.io/mixnet/${{ env.APP_NAME }}:${{ steps.appinfo.outputs.version }}"
            "docker.io/mixnet/${{ env.APP_NAME }}:latest"
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install --global yarn
      #- name: generateReleaseNote
      #  run: yarn run release-note
      #- name: Release
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    tag_name: "mixnet/release:${{ steps.appinfo.outputs.version }}"
      #    name: Release ${{ steps.appinfo.outputs.version }}"
      #    body_path: CHANGE.md
      #- name: updateVersionToApiServer
      #  run: |
      #    curl -X POST "${{ secrets.VERSIONURL }}${{ steps.appinfo.outputs.version }}"
      #- name: 部署到集群
      #  uses: steebchen/kubectl@v2.0.0
      #  with: # defaults to latest kubectl binary version
      #    config: ${{ secrets.K8S_CONFIG_DATA }}
      #    command: set image  deployment/vanblog vanblog=docker.io/mixnet/vanblog:${{ steps.appinfo.outputs.version }}
      #- name: 部署 demo 到集群
      #  uses: steebchen/kubectl@v2.0.0
      #  with: # defaults to latest kubectl binary version
      #    config: ${{ secrets.K8S_CONFIG_DATA }}
      #    command: set image  deployment/blogdemo vanblog=docker.io/mixnet/vanblog:${{ steps.appinfo.outputs.version }}
