name: GitHub Actions Build and Deploy Page
on:
  push:
    tags: 
      - "v*"
    branches:
      - main
env:
  Project_Name: vmgc

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        id: project
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise,  the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
  
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm i -g yarn asar replace-in-files-cli

      - name: 读取当前版本号
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./build/electron/package.json
          property: version

      - name: Build Page
        run: |
          echo "version ${{ steps.version.outputs.value }} "
          export VITE_API_SERVER=${{ vars.API_SERVER }}
          export VITE_APP_TITLE=${{ vars.APP_TITLE }}
          export VITE_APP_DESC=${{ vars.APP_DESC }}
          export VITE_APP_CODE=${{ vars.APP_CODE }}
          export VITE_APP_ORG="${{ vars.APP_ORG }}"
          export VITE_APP_UPDATE_URL="${{ vars.APP_UPDATE_URL }}"
          export VITE_APP_URL="${{ vars.APP_URL }}"
          export VITE_APP_SCRIPT_URL="${{ vars.APP_SCRIPT_URL }}"

          echo "pwd===" && pwd
          echo "VITE_APP_CODE [ $VITE_APP_CODE ] [ ${{ vars.APP_CODE }} ]"
          sed -i 's/vmgc/${{ vars.APP_CODE }}/g' ./package.json

          if [ $VITE_APP_SCRIPT_URL ];then
            replace-in-files --string='/js/head.js' --replacement='${{vars.APP_SCRIPT_URL}}'  ./index.html
          fi

          rm -rf node_modules && yarn install
          yarn build
          mkdir ./dist/caches
          mv ./build/electron/package.json ./dist/caches
          mv ./build/electron/afterpack*.js ./dist/caches

          if [ $VITE_APP_TITLE ];then
            replace-in-files --string='%VITE_APP_TITLE%' --replacement='${{vars.APP_TITLE}}'  ./dist/index.html
          fi
          if [ $VITE_APP_DESC ];then
            replace-in-files --string='%VITE_APP_DESC%' --replacement='${{vars.APP_DESC}}'  ./dist/index.html
          fi
          if [ $VITE_APP_CODE ];then
            sed -i 's/vmgc/${{ vars.APP_CODE }}/g' ./dist/caches/package.json
          fi
          if [ $VITE_APP_ORG ];then
            sed -i 's/vmxy/${{ vars.APP_ORG }}/g' ./dist/caches/package.json
          fi
          if [ $VITE_APP_UPDATE_URL ];then
            echo "replace VITE_APP_UPDATE_URL"
            replace-in-files --string='APP_UPDATE_URL' --replacement='${{vars.APP_UPDATE_URL}}'  ./dist/caches/package.json
          fi

          mkdir ./dist/electron
          mv ./build/electron/electron*.js ./dist/electron/
          sed -i '1i globalThis.APP_CODE="${{ vars.APP_CODE }}";' ./dist/electron/electron.js
          sed -i '1i globalThis.APP_UPDATE_URL="${{ vars.APP_UPDATE_URL }}";' ./dist/electron/electron.js

          asar pack ./dist app-v${{steps.version.outputs.value}}.asar
          zip -r app-v${{steps.version.outputs.value}}.zip ./dist
          
          mv app-v${{steps.version.outputs.value}}.asar ./dist
          mv app-v${{steps.version.outputs.value}}.zip ./dist

          cd dist && ls -lh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        #uses: actions/upload-artifact@v3
        with:
          # Upload entire repository
          path: "./dist"
          

  # Deployment job
  electron:
    environment:
      name: github-pages
    #runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest] #windows-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 读取当前版本号
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./build/electron/package.json
          property: version

      - run: cd ../
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          path: ../
      
      - name: Build Macos and Linux
        if: runner.os == 'Linux' || runner.os == 'macos'
        run: |
          export APP_UPDATE_URL=${{ vars.APP_UPDATE_URL }}
          cd ../
          # cp -r ${{ env.Project_Name }} project
          mv -f ./github-pages ./app
          cd ./app
          tar -xf artifact.tar && rm -rf artifact.tar
          cd caches && ls -lh && cd ..
          cd ../

          cp ./app/caches/package.json ./
          cp -f ./app/caches/afterpack.*.js ./
          rm -rf ./app/caches
          
          pwd && ls -lh
          yarn install
          yarn build
          ls
          cd build-app && ls -ls && cd ../
          mkdir artifact

      - name: Copy macos
        if: runner.os == 'Macos'
        run: |
          cd ../
          cp -f build-app/latest-mac.yml artifact/
          cp -f build-app/*.dmg artifact/
          cp -f build-app/*.dmg.blockmap artifact/
          cp -f build-app/*.zip artifact/
          cp -f build-app/*.zip.blockmap artifact/
          
      - name: Copy Linux
        if: runner.os == 'Linux'
        run: |
          cd ../
          cp -f build-app/latest-linux.yml artifact/
          cp -f build-app/*.AppImage artifact/
          cp -f build-app/*.snap artifact/
          cp -f app/app-*.asar artifact/
          cp -f app/app-*.zip artifact/
          
      - name: Build Windows
        if: runner.os == 'windows'
        run: |
          set APP_UPDATE_URL=${{ vars.APP_UPDATE_URL }}
          cd ../
          # xcopy ${{ env.Project_Name }} project /E/I
          move github-pages app

          cd app
          tar -xf artifact.tar && del artifact.tar
          cd ..

          copy app\caches\package.json .
          copy app\caches\afterpack.*.js .
          move app\caches .\
          

          yarn install
          yarn build

          cd build-app && ls  && cd ..
          mkdir artifact
          copy build-app\latest.yml artifact\
          copy build-app\*.exe artifact\
          copy build-app\*.blockmap artifact\
          copy build-app\*.zip artifact\
          copy build-app\*.appx artifact\

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        #uses: actions/upload-artifact@v3
        with:
          # Upload entire repository
          name: ${{ runner.os }}
          path: "../artifact"

  merge-artifact:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: [build, electron]
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          path: ./

      - name: Handle
        run: |
          echo "===========handle github-pages"
          cd github-pages
          tar -xf artifact.tar && rm artifact.tar
          ls
          cd ..
          echo "===========handle linux"
          cd Linux
          tar -xf artifact.tar && rm artifact.tar
          ls
          cd ..
          echo "===========handle macOS"
          cd macOS
          tar -xf artifact.tar && rm artifact.tar
          ls    
          cd ..  
          echo "===========handle Windows"
          cd Windows
          tar -xf artifact.tar && rm artifact.tar
          ls    
          cd .. 

      - name: merge
        run: |
          pwd
          echo "============merge=============="
          ls -lh
          mkdir github-pages/apps
          cp Linux/* github-pages/apps
          cp macOS/* github-pages/apps
          cp Windows/* github-pages/apps
          mv github-pages/*.asar github-pages/apps
          mv github-pages/*.zip github-pages/apps
          echo "============show github-pages=============="
          rm -rf github-pages/caches
          cd github-pages && ls -lh
          
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        #uses: actions/upload-artifact@v3
        with:
          # Upload entire repository
          path: "./github-pages"

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: merge-artifact
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2


