name: Build Android

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Build
        run: |
          npm i -g yarn
          yarn
          pwd && ls -lh
          yarn build 
          cd capacitor
          pwd && ls -lh
          yarn 
          yarn sync
          cp -f android/app/src/main/res/layout/activity_main.xml ./node_modules/@capacitor/android/capacitor/src/main/res/layout/bridge_layout_main.xml
          cd android           
          pwd && ls -lh
          cd app/
          #Extract Android signing key from env
          echo "${{ secrets.RELEASE_KEYSTORE }}" > release.jks.base64
          base64 -d release.jks.base64 > release.jks
          cd ../ 
          chmod +x ./gradlew
          ./gradlew assembleRelease
          pwd && ls -lh
          cd app/build/outputs/apk/office/release && pwd && ls -lh

          # Sign dev build
          # jarsigner -keystore release.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab release

      - name: Upload release bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: capacitor/android/app/build
          retention-days: 60